@dev_url=http://localhost:3958/v1/api


POST url HTTP/1.1
Content-Type: application/soap+xml
header name: header value

<soap:Envelope
    xmlns:soap="http://www.w3.org/2001/12/soap-envelope"
    soap:encodingStyle="http://www.w3.org/2001/12/soap-encoding">
    <soap:Body>
        content
    </soap:Body>
</soap:Envelope>

### signup
POST {{dev_url}}/shop/signup
Content-Type: application/json
x-api-key: fed64605bd36f981d3db02a5e24830c95eb5028183cebf99b090a04cbc2e6373e8b5437ba57c716420630272c81a2ff41dba67927029b4e672ce9f5f50396aae

{
"name": "Shophfg",
    "email": "sd2212@gmail.com",
    "password": "shophfg"
}